

```{r}
library(DESeq2)
library(ggplot2)
#library(tidyverse)
library(ComplexHeatmap)
library("org.Hs.eg.db")
library(clusterProfiler)
library(enrichplot)
library(DOSE)
library(AnnotationDbi)
library(RColorBrewer)
```

## Correlated gene with ECM score running GSEA

```{r}
genesets <- read.delim("Gene_correlate_with_stiffness_score.csv",sep = ",", header = FALSE)
rownames(genesets) <- genesets$V1
genesets$V1 <- NULL


```




```{r}

#order based on correlation

selected <- genesets[genesets$V2 > 0,]
selected <- selected[!isNA(rownames(selected)),]
selected <- selected[-dim(selected),]
gene_list <- selected$V2
names(gene_list) <- rownames(selected)



```


```{r}
gse <- gseGO(gene_list,
             ont= "BP",
             keyType = "SYMBOL",
             scoreType = "pos",
             #minGSSize = 50, 
             #maxGSSize = 800, 
             pvalueCutoff = .05, 
             verbose = TRUE,
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300,
             pAdjustMethod = "BH")
```


```{r}

gse.df <- as.data.frame(gse)
gse.df
```



```{r}

gsea_dotplot <- dotplot(gse, showCategory = 20 , font.size = 8, x = "NES") + 
  geom_point(aes(size=Count, color= qvalue)) +
  scale_color_gradientn(colors = rev(brewer.pal(4, "OrRd"))) +
  theme(panel.grid = element_line()) +
  labs(color = "FDR")

gsea_dotplot

```

```{r}
#print
# save as pdf
ggsave("gsea_dotplot_3dcc_vs_3dnc_v2.pdf", gsea_dotplot, width = 8, height = 6)


```

